### ISSUE TITLE
Would you kindly release the benchmark in the near future ?

### ISSUE THREAD

**Issue by prefixRAINSTARsuffix** [yale-nlp/DocMath-Eval#1]
Thanks for the impressive work. We are looking forward to the release of the benchmark.

**Comment by YvetteLaw** [comment]
+1

**Comment by yilunzhao** [comment]
Hi @prefixRAINSTARsuffix, @YvetteLaw, thanks for your interests in our work! We plan to release the benchmark by the end of this month. I will let you when it is publicly available.
