### ISSUE TITLE
Discrepancy in Results with Provided Code

### ISSUE THREAD

**Issue by NamespaceY** [yale-nlp/DocMath-Eval#5]
Hello, I am currently working with your paper and have been using the code provided in your GitHub repository. However, I have encountered a discrepancy between the results I obtained and those reported in the paper.

After running the script scripts/inference/run_retriever.sh with the parameters `models = ("bm25")` and `sets = ("complong_testmini")`, the output recall does not align with the results stated in the paper after executing scripts/evaluation/evaluate_retriever_recall.sh.

Top 3 Results:
![image](https://github.com/user-attachments/assets/2af54351-ffe6-4fc2-b5c6-575b77b7d4d7)

Top_5 Result:
![image](https://github.com/user-attachments/assets/528cbb9a-bf34-4674-b41c-f5ffae402072)

Top_10 Result:
![2024-10-29 113031](https://github.com/user-attachments/assets/28c111f3-9089-482e-9693-c5fb9a090e17)

Results from the Paper::
![image](https://github.com/user-attachments/assets/f96577b4-be3a-4056-80a5-ee8a279292e6)

run_retriever.sh:
~~~ shell
#!/bin/bash

export CUDA_VISIBLE_DEVICES=1,2

models=(
    "bm25"
)

sets=(
  "complong_testmini"
)

top_ks=(
  3
  5
  10
)

api_base="TODO"
api_key="TODO"

for model in "${models[@]}"; do
  for set in "${sets[@]}"; do
    echo "Running embedding for model: $model on $set set with top_k: $k"

    python retriever/retriever.py \
        --model_name "$model" \
        --subset "$set" \
        --top_k -1 \
        --api_base "$api_base" \
        --api_key "$api_key"
  done
done

for model in "${models[@]}"; do
  for set in "${sets[@]}"; do
    for k in "${top_ks[@]}"; do
      echo "Running embedding for model: $model on $set set with top_k: $k"

      model_name=$(echo $model | awk -F'/' '{print $NF}')
      input_file="retrieved_output/$set/all/${model_name}.json"
      output_dir="retrieved_output/$set/top_$k"
      python retriever/get_top_n.py \
          --input_file "$input_file" \
          --output_dir "$output_dir" \
          --top_k "$k"
    done
  done
done
~~~ 

I also modified the code in the `recall_evaluation.py` file to load the dataset from HuggingFace instead of loading it from a local file.
![image](https://github.com/user-attachments/assets/0b9b702a-59b6-45b1-891d-405d5a2fadce)

I would appreciate any guidance you could provide regarding this issue. Are there any specific configurations or additional steps that I might have missed?

Thank you for your time, and I look forward to your response.

**Comment by yilunzhao** [comment]
Hi @NamespaceY, thanks for your interests in our work! Could you please take a look at our previous posts at https://github.com/yale-nlp/DocMath-Eval/issues/3#issuecomment-2395621099. The discrepancy you mentioned could be related to the data preprocessing steps. Let me know if you have any questions!

Additionally, we welcome any contributions! So please don’t hesitate to submit a PR if you see opportunities for improvement in the code.

**Comment by NamespaceY** [comment]
Thank you for your prompt and helpful response! I reviewed the previous posts you mentioned and made the necessary adjustments to the data preprocessing steps. I now have results that are consistent with those in the paper.

Thanks again for your assistance!
